### PR TITLE
Cross build with 2.11 and 2.12

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Review by @adriaanm 

I will prepare similar PRs for the other modules once this LGTY.

**Comment by lrytz** [comment]
Important pieces of the [build log](https://travis-ci.org/scala/scala-xml/jobs/61438335):

```
/usr/lib/jvm/java-6-openjdk-amd64/bin/java
-Xms2048M
-Xmx2048M
-Xss6M
-XX:MaxPermSize=512M
-jar
/home/travis/.sbt/launchers/0.13.8/sbt-launch.jar
clean
update
+test

[info] Setting version to 2.11.6
[info] scala-xml: found 0 potential binary incompatibilities
[info] Passed: Total 90, Failed 0, Errors 0, Passed 90

[info] Setting version to 2.12.0-M1
[warn] MiMa will NOT run because the previous artifact "org.scala-lang.modules" % "scala-xml_2.12.0-M1" % "1.0.1" could not be resolved (note the binary Scala version).
[info] Passed: Total 90, Failed 0, Errors 0, Passed 90

The command "admin/build.sh" exited with 0.
```

**Comment by adriaanm** [comment]
LGTM!

**Comment by adriaanm** [comment]
Thanks for including the build log snippet 👌

**Comment by lrytz** [comment]
integrated the new scripts from https://github.com/scala/scala-java8-compat/commit/4a6cfc97cd95227b86650410e1b632e5ff79335b

**Comment by lrytz** [comment]
merging. i will create a -TEST tag to make sure publishing works.

**Comment by lrytz** [comment]
publishing worked, including cross-building (https://travis-ci.org/scala/scala-xml/jobs/62079369)

**Pull request merged**
