### PR TITLE
Update For Dotty 0.28.0-bin-20200904-1ab71c1-NIGHTLY

### PR DESCRIPTION
**Pull request by isomarcte**
The only changes where some ambiguous references to symbols.

### CODE REVIEW

**Comment by SethTisue** [comment]
we don't normally target Dotty nightlies. what would the motivation be for doing so in this case?

**Comment by isomarcte** [comment]
@SethTisue I wasn't sure what the policy was on that. My personal motivation for this PR was just to get `scala-xml` up to a relatively recent dotty version so I could validate it against another project which has `scala-xml` as a dependency. 

I'd be happy to leave this PR as is and wait for `0.28.0-RC1` at which time I'll re-update it for that release, as you suggested. If that is agreeable to you, I'd be happy to open a new PR for `0.27.0-RC1` (other than the version number I expect it is likely the same code changes).

How does that sound?

**Comment by SethTisue** [comment]
SGTM. I merged the other PR and marked this one was "draft". Thank you!

**Comment by SethTisue** [comment]
3.0.0-M1 is available now

**Comment by isomarcte** [comment]
@SethTisue I'll update this

**Comment by SethTisue** [comment]
3.0.0-M2 is on Maven Central

**Comment by isomarcte** [comment]
@SethTisue I closing this in favor of https://github.com/scala/scala-xml/pull/470

**Pull request closed without merging**
