### PR TITLE
speed up Travis builds using caching feature

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
oops, a second run still gives:

```
change detected (content changed, file is created, or file is deleted):
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/bundles/scala-xml_2.11.jar
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/bundles/scala-xml_2.11.jar.md5
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/bundles/scala-xml_2.11.jar.sha1
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/docs/scala-xml_2.11-javadoc.jar
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/docs/scala-xml_2.11-javadoc.jar.md5
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/docs/scala-xml_2.11-javadoc.jar.sha1
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/ivys/ivy.xml
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/ivys/ivy.xml.md5
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xml_2.11/1.0.6-SNAPSHOT/ivys/ivy.xml.sha1
/home/travis/.ivy2/local/org.scala-lang.modules/scala-xm
```

I'll fix...

**Comment by SethTisue** [comment]
screen shot 2017-02-04 at 9 57 03 am

looks like this cuts the build time from almost 4 minutes to about 2 minutes.

**Comment by SethTisue** [comment]
I'll take the thumbs-ups and the lack of other feedback as a goahead to merge.

**Comment by ashawley** [comment]
Indeed.  I rebased a bunch of PRs, and it's a lot faster.

https://travis-ci.org/scala/scala-xml/pull_requests

**Comment by gourlaysama** [comment]
Awesome! 👍 
I shamelessly did the same over at scala/scala-parser-combinators#100.

**Pull request merged**
