### PR TITLE
Cleanup for release 2.1.0

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by SethTisue** [comment]
(I closed/reopened after deleting the 2.0.2 tag, as discussed at on #596.)

**Comment by catap** [comment]
@SethTisue a force push to trigger CI

**Comment by catap** [comment]
@SethTisue I need a coffee and will make a few more pushes here, I'll ping you when CI has a green mark.

**Comment by SethTisue** [comment]
From the CircleCI failure, it appears that Scala Native needs an adjustment.

**Comment by SethTisue** [comment]
I've invited you to https://github.com/scala/scala-xml/settings/access (with "Triage" access) so I don't need to keep hitting "Approve" to let GitHub Actions run.

**Comment by catap** [comment]
> I've invited you to https://github.com/scala/scala-xml/settings/access (with "Triage" access) so I won't need to keep hitting "Approve" to let GitHub Actions run.

I haven't got any email of this nor access to it :(

**Comment by SethTisue** [comment]
> I haven't got any email of this nor access to it :(

gah, I invited the wrong "catap". fixed I think, check again

**Comment by catap** [comment]
Let's wait some time until `2.1.0` is available via maven central. I'll be back here in couple of hours.

**Comment by catap** [comment]
@SethTisue as expected: it is green now :)

**Pull request merged**
