### PR TITLE
scala-js 0.6.23. fix warnings

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by ashawley** [comment]
What were the warnings?  I'm working in a branch on updating scala-xml to 2.13.0-M4, and had updated to scala-js 0.6.23, but didn't see any warnings.

**Comment by xuwei-k** [comment]
```
build.sbt:18: warning: method crossProjectFromBuilder in trait CrossProjectExtra is deprecated: The built-in cross-project feature of sbt-scalajs is deprecated. Use the separate sbt plugin sbt-crossproject instead: https://github.com/portable-scala/sbt-crossproject
lazy val xml = crossProject.in(file("."))
               ^
```

https://github.com/scala-js/scala-js/blob/v0.6.23/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/cross/CrossProject.scala#L370-L374

**Comment by xuwei-k** [comment]
https://travis-ci.org/scala/scala-xml/jobs/380530645#L631-L633

**Comment by ashawley** [comment]
Fixed in #223.

**Pull request closed without merging**
