### PR TITLE
Allow publishing existing tags against new Scala versions

### PR DESCRIPTION
**Pull request by lrytz**
This should include all changes proposed in https://github.com/scala/scala-xml/pull/141

### CODE REVIEW

**Comment by ashawley** [comment]
@lrytz We're just waiting on a scalajs build for 2.13.0-M1?

**Comment by lrytz** [comment]
Ah yes, it seems so. I heard this should happen soon, if there's nothing unexpected.

**Comment by SethTisue** [comment]
Sebastien says 0.6.16 should be out later this week (0.6.15 cannot be published for 2.13)

**Comment by lrytz** [comment]
This is ready now, the cross-build with 2.13.0-M1 passed.

**Pull request merged**
