### PR TITLE
add -Xfuture option. fix procedure syntax warnings

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by ashawley** [comment]
Thanks for doing this, Kenji.  

Your commit message says "add -Xfuture option."  Did you forget to include a file?  Maybe build.sbt?

**Comment by xuwei-k** [comment]
> Did you forget to include a file? Maybe build.sbt?

Oops. fixed

**Comment by ashawley** [comment]
Hey @SethTisue, is `-Xfuture` something we can consider enabling or does it cause a time warp in either the community build universe or compiler bootstrap?  I'm thinking of a scenario where a new `-Xfuture` compiler error could keep the bootstrap process from working.  Maybe you could think of other scenarios.

**Comment by SethTisue** [comment]
I would not suggest using `-Xfuture` except possibly as an alternate additional testing path — not by default. It isn't something you want enabled in a release build. (Not because of bootstrapping in particular, just general concerns about quality. You want to use the best-tested version of the compiler for doing release builds of core libraries.)

`-Xfuture` may go away anyway in 2.13: https://github.com/scala/scala-dev/issues/471

**Comment by ashawley** [comment]
I'll merge, but undo `-Xfuture` and add a note per Seth's comments.

**Pull request merged**
