### PR TITLE
Fix doBuildString for TopScope of NamespaceBinding

### PR DESCRIPTION
**Pull request by muntis**
Sugested fix for https://github.com/scala/scala-xml/issues/45

### CODE REVIEW

**Comment by ashawley** [comment]
This bug is a good find.  I don't think overriding `doBuildString` in `NamespaceBinding` is necessary to fix it.  I think this defect is similar to the other issues where the library should be recognizing `TopScope` in addition to `null`.   I'll try to add a commit here.

**Comment by ashawley** [comment]
Ignore my commit, I forgot I had already submitted something to #45

**Comment by SethTisue** [comment]
needs rebase now

any reviewers out there with an opinion on this...?

**Comment by ashawley** [comment]
@SethTisue This can be closed, since it was fixed in #91

**Comment by SethTisue** [comment]
oh haha we never actually got you the access to close tickets. I invited you to https://github.com/orgs/scala/teams/community-maintainers just now, so after accepting that invite you should be able to close it yourself.

**Comment by ashawley** [comment]
@muntis I fixed #45 in #91, so I'm closing this PR you made.  Thanks again for sending this and the original bug report.

**Comment by muntis** [comment]
Thanks!

**Pull request closed without merging**
