### PR TITLE
New scala-module-plugin with sbt-ci-release / travisci / dynver / header

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
Cherry-picked https://github.com/scala/scala-xml/pull/355 into this PR.

**Comment by lrytz** [comment]
See here where we discussed these changes: https://github.com/scala/sbt-scala-module/pull/65#issuecomment-531142475

**Comment by ashawley** [comment]
These changes look fine to me.  If we have issues, we'll cross them when we get to them.  

There are no planned releases from `master` in the near future and the library is pretty stable, so you should feel free to experiment here.

Thanks for keeping the build and release infrastructure updated!

**Comment by lrytz** [comment]
Thanks, @ashawley! I'll rebase to fix the conflicts and merge.

**Comment by lrytz** [comment]
Tested the release process with a test tag, everything looked fine. Dropped the tag and the staging repos.

**Pull request merged**
