### PR TITLE
Fix ignored stripComments parameter of Utility.serialize

### PR DESCRIPTION
**Pull request by olafos**
Fixes issue #183 - stripComments parameter not working

### CODE REVIEW

**Comment by ashawley** [comment]
Thanks for fixing this and including a test.  

Looks good to me.  Want to amend the commit and use the e-mail you use with GitHub?

```bash
$ git commit --amend --author 'Olaf Tomczak <your@email>'
```

While you're at it, aybe a more descriptive commit message than "Fix 183"?

**Comment by olafos** [comment]
Yep, sorry - hope it's acceptable now ;)

**Comment by ashawley** [comment]
Closed by c924667

**Comment by ashawley** [comment]
Thanks for fixing up.  There was an extra merge commit, but I was able to get it across the finish line.  Thanks again for fixing the bug.

**Pull request closed without merging**
