### PR TITLE
Fix #51 (replaces #61)

### LINKED ISSUE #51: CDATA test broken
Since https://github.com/scala/scala/pull/4306:
```
> set every scalaVersion := "2.11.7-SNAPSHOT"
test
[info] Defining */*:scalaVersion, *:scalaVersion
[info] The new values will be used by */*:crossScalaVersions, */*:scalaBinaryVersion and 14 others.
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] Set current project to scala-xml (in build file:/Users/adriaan/git/scala-xml/)
> test
[warn] Credentials file /Users/adriaan/.ivy2/.credentials does not exist
[info] Updating {file:/Users/adriaan/git/scala-xml/}scala-xml...
[info] Resolving org.scala-lang#scala-compiler;2.11.7-SNAPSHOT ...
[warn] circular dependency found: org.scala-lang.modules#scala-xml_2.11;1.0.4-SNAPSHOT->org.scala-lang#scala-compiler;2.11.7-SNAPSHOT->org.scala-lang.modules#scala-xml_2.11;1.0.3
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-library/2.11.7-SNAPSHOT/scala-library-2.11.7-20150413.015800-17.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.11.7-SNAPSHOT!scala-library.jar (3021ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-compiler/2.11.7-SNAPSHOT/scala-compiler-2.11.7-20150413.015800-17.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-compiler;2.11.7-SNAPSHOT!scala-compiler.jar (7544ms)
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scala-reflect/2.11.7-SNAPSHOT/scala-reflect-2.11.7-20150413.015800-17.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-reflect;2.11.7-SNAPSHOT!scala-reflect.jar (2763ms)
[info] Done updating.
[info] Compiling 84 Scala sources to /Users/adriaan/git/scala-xml/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.7-20150410-102911-6e7b32649b. Compiling...
[info]   Compilation completed in 13.95 s
[warn] there were two deprecation warnings; re-run with -deprecation for details
[warn] one warning found
[info] Compiling 15 Scala sources to /Users/adriaan/git/scala-xml/target/scala-2.11/test-classes...
[info] scala-xml: found 0 potential binary incompatibilities
[warn] there was one deprecation warning; re-run with -deprecation for details
[warn] there were 42 feature warnings; re-run with -feature for details
[warn] two warnings found
:9:19: '/' expected instead of ''                  ^
:9:19: name expected, but char '' cannot start a name                  ^
Testing scala-xml version 1.0.4-SNAPSHOT.
Testing scala-xml version 1.0.4-SNAPSHOT.
Testing scala-xml version 1.0.4-SNAPSHOT.
Testing scala-xml version 1.0.4-SNAPSHOT.
[error] Test scala.xml.XMLTest.escape failed: expected:<[
[error]  &quot;Come, come again, whoever you are, come!
[error] Heathen, fire worshipper or idolatrous, come!
[error] Come even if you broke your penitence a hundred times,
[error] Ours is the portal of hope, come as you are.&quot;
[error]                               Mevlana Celaleddin Rumi]> but was:<[<![CDATA[
[error]  "Come, come again, whoever you are, come!
[error] Heathen, fire worshipper or idolatrous, come!
[error] Come even if you broke your penitence a hundred times,
[error] Ours is the portal of hope, come as you are."
[error]                               Mevlana Celaleddin Rumi]]>]>
[error] Failed: Total 88, Failed 1, Errors 0, Passed 87
[error] Failed tests:
[error] 	scala.xml.XMLTest
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 65 s, completed Apr 13, 2015 2:20:44 PM
```

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by som-snytt** [comment]
Thx, @SethTisue .  I think `-Xfatal-warnings` is required for street cred.

I'm going to order the t-shirt in black, where the `X` is a skull and crossbones, and `fatal-warnings` is in pseudo-Gothic typeface where the `f` looks like a dagger and there's an incongruous umlaut over the `a` in `warnings`.

**Comment by SethTisue** [comment]
I was finally able to do a test run of integrate-bootstrap in the scala/scala repo using the code from this PR, and it worked: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-bootstrap/97/consoleFull

**Comment by som-snytt** [comment]
:clap: :fireworks: What a vicarious thrill.

**Comment by SethTisue** [comment]
I'm live-blogging the gory details at https://github.com/scala/scala/pull/4658

**Pull request merged**
