### PR TITLE
Changes in preparation for the 2.13 collections

### PR DESCRIPTION
**Pull request by lrytz**
Changes uses of `scala.Seq` to `collection.Seq`, as in 2.13 the `scala.Seq` alias changes to be `scala.immutable.Seq`.

Some other changes that enable cross-building 2.11 ---> 2.13.

Also update the sbt-scala-module plugin.

### CODE REVIEW

**Comment by SethTisue** [comment]
I guess this would have to be a 1.2 release...?

**Comment by lrytz** [comment]
This PR not, it's binary compatible.

**Comment by SethTisue** [comment]
oh, duh, right.

**Comment by lrytz** [comment]
Note that this PR doesn't allow building with the new collections yet, it just includes those changes that cross-build.

For the rest, there will be another PR once 2.13.0-M4 is out. These changes are here: https://github.com/scala/scala-xml/compare/v1.1.0-newCollections

**Comment by ashawley** [comment]
The badges on the README are a little goofed up:

maven badges are screwy

**Comment by lrytz** [comment]
sorry about the tags.. it just picks the most recent release.

**Comment by ashawley** [comment]
Yeah, sorry.  We fixed procedure syntax warnings in #207.

**Comment by ashawley** [comment]
Merged in #210

**Pull request closed without merging**
