### PR TITLE
Remove some unneeded semicolons and the like.

### PR DESCRIPTION
**Pull request by dubinsky**

### CODE REVIEW

**Comment by dubinsky** [comment]
@SethTisue is there anything I  can do for this to be merged? Thanks!

**Comment by SethTisue** [comment]
(I can take a look in January, if no other reviewer has volunteered by then.)

**Comment by SethTisue** [comment]
very nice! thanks

**Comment by dubinsky** [comment]
Thank you; the pleasure is mine ;)

**Pull request merged**
