### PR TITLE
SI-9060: Accept fifth-edition names.

### PR DESCRIPTION
**Pull request by som-snytt**
Accept fifth-edition names.

Fix infinite loopiness in attribute parsing.

Improve tests a bit.

### CODE REVIEW

**Comment by SethTisue** [comment]
@som-snytt needs rebase. as you've probably seen, I'm doing a sweep over this repos open PRs, trying to ascertain their status and seeing if there's anything that can be merged. is this PR still relevant, and would you be interested in getting it over the finish line?

**Comment by som-snytt** [comment]
The conflicts are trivial -- git is amazing -- but are the maintainers going to merge it or what? I haven't used xml in a decade. Do they care?

**Comment by SethTisue** [comment]
> The conflicts are trivial -- git is amazing -- but are the maintainers going to merge it or what? I haven't used xml in a decade. Do they care?

if you rebase it, I will personally make sure it gets merged (if no one raises substantive objections)

**Comment by SethTisue** [comment]
oh, you know what? actually, never mind, let's go with #44 instead, sorry for missing that before.

**Pull request closed without merging**
