### PR TITLE
test Travis-CI on JDK 17

### PR DESCRIPTION
**Pull request by SethTisue**
Travis-CI is failing because SDKMAN isn't finding JDK 17 anymore. 

Not sure what changed. Is scala/scala-dev@1a7c0e6ce46f611686d38a0ae96ca51528352038 not right anymore?

### CODE REVIEW

**Comment by SethTisue** [comment]
https://github.com/scala/scala-dev/commit/47118f13eeb6bf1a5a3080856c69aab9e2507278#diff-f4dff8443b496634d47500e60fd050b98480f2ee7b16635c2d5c43d131a9c398 gives us additional debugging output

and now at https://app.travis-ci.com/github/scala/scala-xml/jobs/536511441 we see that the only Java.net build of 17 available is `17.ea.3.pma`; there used to also be `17.ea.28`

also confirmed by this by running `sdk list java` locally on my Mac and I see:

```
               | >>> | 17.ea.28     | open    | local only | 17.ea.28-open       
               |     | 17.ea.3.pma  | open    |            | 17.ea.3.pma-open    
```

where the "local only" business seems to confirm that the SDKMAN folks somehow pulled it from availability

**Comment by SethTisue** [comment]
what is `17.ea.3.pma`, is it suitable for our use? my best guess is that "pma" is short for Project Panama, as in https://jdk.java.net/panama/ , and if I'm right, then no it is not suitable

**Comment by SethTisue** [comment]
there's no recent changes at https://github.com/sdkman/sdkman-db-migrations/commits/master/src/main/scala/io/sdkman/changelogs/java/OpenJdkMigrations.scala 🤷

**Comment by ashawley** [comment]
SDKMAN needs to be updated to retrieve build 35? https://jdk.java.net/17/

**Comment by ashawley** [comment]
It's strange, because looking at old Travis builds from last week, it appears SDKMAN had no trouble pulling down build 33:

```
Using java version 17.ea.33-open in this shell.
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+33-2705)
OpenJDK 64-Bit Server VM (build 17-ea+33-2705, mixed mode, sharing)
```

**Comment by SethTisue** [comment]
I've reported it at https://github.com/sdkman/sdkman-candidates/issues/38

If this isn't resolved in the next few days I think we could just temporarily remove JDK 17 from the matrix until there's a fix or until JDK 17 final becomes available from the AdoptOpenJDK folks, whichever occurs first.

**Comment by SethTisue** [comment]
umbrella ticket on handling this org-wide (all scala/* repos): https://github.com/scala/scala-dev/issues/787

**Comment by SethTisue** [comment]
I believe this is fixed now based on what I've seen in other repos

**Pull request closed without merging**
